AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  okta-workflow-metrics

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    MemorySize: 512

Resources:
  OktaWorkflowMetricsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: okta-workflow-metrics-function/
      Handler: app.lambda_handler
      Runtime: ruby3.3
      Architectures:
        - x86_64
      Events:
        OktaWorkflowMetrics:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Auth:
              ApiKeyRequired: true
            Path: /<api-endpoint-path>
            Method: post

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  OktaWorkflowMetricsApi:
    Description: "API Gateway endpoint URL for Prod stage for Okta Workflow Logs function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/<api-endpoint-path>"
  OktaWorkflowMetricsFunction:
    Description: "Okta Workflow Logs Lambda Function ARN"
    Value: !GetAtt OktaWorkflowMetricsFunction.Arn
  OktaWorkflowMetricsFunctionIamRole:
    Description: "Implicit IAM Role created for OktaWorkflowMetrics function"
    Value: !GetAtt OktaWorkflowMetricsFunctionRole.Arn
